[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "python3 -m uvicorn api:app --host 0.0.0.0 --port $PORT"
