[build]
builder = "NIXPACKS"
buildCommand = "cd ml-service && pip install -r requirements.txt"

[deploy]
startCommand = "cd ml-service && uvicorn api:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
